config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  #RESOURCE
  #Todo is a resource
  # - list of resources can be seen :index
  # - single resource can be seen : show
  # - create a resource
 
  #match '/todos'=> 'todos#index', via: :get
  # get "todos",to:"todos#index"
  # get "todos/:id",to:"todos#show"
  # patch "todos/:id",to:"todos#update"
  get "/",to:"home#index"
  resources :todos
  resources :users
  get "/signin",to:"sessions#new",as: :new_sessions
  post "/signin",to:"sessions#create",as: :sessions
  delete "/signout",to:"sessions#destroy",as: :destroy_sessions
  # get "user",to:"user#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
require 'active_record'
require "date"
class Todo<ActiveRecord::Base
    validates :todo_text, presence: true
    validates :due_date, presence: true
    validates :todo_text, length: { minimum: 2}
    belongs_to :user
    
    def to_displayable_string 
        display_status = completed ? "[X]" : "[ ]" 
        "#{id}. #{display_status} #{todo_text} #{due_date}"  
    end
    def self.to_displayable_string
        all.map{|todo| todo.to_displayable_string}
    end
    def self.of_user(user)
        all.where(user_id: user.id)
    end
    
    def self.overdue
        all.where("due_date < ?", Date.today)
    end
    def self.due_today
        all.where(due_date: Date.today)
    end
    def self.due_later
        all.where("due_date > ?", Date.today)
    end
    def self.completed?
        all.where(completed:true)
    end

end

app/models/user.rb
require 'bcrypt'
class User<ActiveRecord::Base
    has_secure_password
    has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session

    before_action :ensure_user_logged_in
    def ensure_user_logged_in
        unless current_user
            redirect_to "/"
        end
    end

    def current_user
        return @current_user if @current_user
        current_user_id=session[:current_user_id]
        if current_user_id
            @current_user=User.find(current_user_id)
        else
            nil
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :ensure_user_logged_in
    def index
        if current_user
            redirect_to todos_path
        else
            render "index"
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :ensure_user_logged_in
    def new
        render "new"
    end
    def create
        user=User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:current_user_id]=user.id
            redirect_to "/"
        else
            flash[:error]="Your login attempt was invalid.Please retry"
            redirect_to new_sessions_path
            
        end
    end
    def destroy
        session[:current_user_id]=nil
        @current_user=nil
        redirect_to "/"
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
        #render plain:Todo.order(:due_date).map {|todo| todo.to_displayable_string}.join("\n")
        @todos=Todo.of_user(current_user)
        render "index"

    end
    def show
        #id=params[:id]
        #todo=Todo.find(id)
        #render plain:todo.to_pleasant_string
        render "todo"
    end
    def create
        todo_text=params[:todo_text]
        due_date=(params[:due_date])
        #check if it is new or create!
        todo=Todo.new(todo_text:todo_text,due_date:due_date,completed:false,user_id:current_user.id)
        if todo.save
            redirect_to todos_path
        else
            flash[:error]=todo.errors.full_messages.join(", ")
            redirect_to todos_path
        end
    end
    def update  
        id=params[:id]
        completed=params[:completed]
        todo=Todo.of_user(current_user).find(id)
        todo.completed=completed
        todo.save!
        redirect_to todos_path
    end
    def destroy
        id=params[:id]
        todo=Todo.of_user(current_user).find(id)
        todo.delete
        redirect_to todos_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :ensure_user_logged_in
    def new
        render "users/new"
    end
    def create
        user=User.create!(
            first_name:params[:first_name],
            last_name:params[:last_name],
            email:params[:email],
            password:params[:password]
            )
            session[:current_user_id]=user.id
           
        redirect_to "/"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="home-title">Welcome to the todo page</h1>

<h3 class="home--authenticate">If you are a new user, <%=link_to "sign up here", new_user_path %></h3>

<h3 class="home--authenticate">If you are a existing user, <%=link_to "sign in here", new_sessions_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'todo-app', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if @current_user%>
    <p class="userheader">
    Welcome <%=@current_user.first_name%>!
    <%= link_to "Signout",destroy_sessions_path,method:"delete"%>
    </p>
    <%end%>
    <%= yield %>
 
  </body>
  <% if flash[:error] %>
  <p class="flash">
  <%= flash[:error] %>
  </p>
  <%end%>
</html>

app/views/todos/_todo-section.html.erb
<section class="s2">
    <div class="d1">
        <p class="p1">
        <%= section_title %>
        </p>
        <p class="p2"><%=todos.completed?.count%> / <%=todos.count%></p>
    </div>
    <ul>
    <% todos.all.each do |todo| %>
        <li class="l1">
            <label class="ll1">
                <%=form_with(url:"/todos/#{todo.id}",method:"put") do %>
                <input class="c1" 
                type="checkbox"
                name="completed"
                <%= todo.completed ? "checked" : ""%>
                onclick="this.form.submit()"
                >
                <%end%>
                <p class='<%= todo.completed ? "todo" : ""%>'>
                <%= todo.todo_text %>
                </p>
               
                <% if show_due_date %>
                    <p class="Todoitem"> <%= todo.due_date.to_s(:short)%> </p>
                <%end%>
                <%= form_with(url:"todos/#{todo.id}", method:"delete") do %> 
                <input type="image" src="trash.png" class="delete">
                <%end%>
            </label>
            </li>
    <%end%>
        
       
    </ul>
   
</section>

app/views/todos/index.html.erb
<main class="m1">      
<article><h1 class="h1h">My To-do List </h1>
<%= form_with(url: "/todos",method: "post",class:"s1") do%>
    <input type="text" placeholder="What's next?" class="textfield1" name="todo_text">
    <input type="date" class="textfield2" name="due_date">
    <input type="submit" value="Add" class="b1" placeholder="Add">
<%end%>


<%= render partial:"todo-section",locals: 
{section_title: "Overdue",
todos: @todos.overdue,
show_due_date:true
} %>
<%= render partial:"todo-section",locals: 
{section_title: "Due today",
todos: @todos.due_today,
show_due_date:false
} %>
<%= render partial:"todo-section",locals: 
{section_title: "Due later",
todos: @todos.due_later,
show_due_date:true
} %>




</article>

app/views/todos/todo.html.erb
<p>This shows a single todo</p>
<% id=params[:id] %>
<% todo=Todo.find(id) %>
<p><%= todo.to_displayable_string %></p>

app/views/users/new.html.erb
<p class="new-user-title"> Welcome new user!</p>

<section class="UsersNew">
<%=form_with url: users_path, method:"post" do |form| %>
    <div class="Form-section">
        <p class= "form-label">First name: </p>
        <%= form.text_field :first_name , class: "form-input" %>
    </div>
    <div class="Form-section">
            <p class="form-label">Last name:</p>
            <%= form.text_field :last_name , class: "form-input"%>
    </div>
    <div class="Form-section">
            <p class="form-label">Email </p>
             <%= form.email_field :email, class: "form-input" %>
    </div>
    <div class="Form-section">
        <p class="form-label">Password </p>
        <%= form.password_field :password, class: "form-input" %>
    </div>
    <%= form.submit"Sign up" ,class:"form-submit" %>
<%end%>
</section>